name: Publish GeoJSON to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install python requirements
      run: pip install -r requirements.txt

    - name: Query overpass and save response as geojson
      run: python3 query_and_convert_to_geojson.py

    # Step 3: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: deploy  # Directory containing the GeoJSON file
